name: Auto Build Snap
on:
  push:
    branches:
      - microk8s-1.30
jobs:
  build:
    name: Build Auto Snap Package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3

      - name: Detect K8s Version.
        run: |
          echo "KUBE_VER=$(echo microk8s-src/build-scripts/components/kubernetes/version.sh | grep -m 1 "KUBE_VERSION=" | sed -E 's/.*=v(([0-9]+\.).*)/\1/')" >> $GITHUB_ENV

      - name: Print K8s Version.
        run: |
          echo $KUBE_VER