name: Test Snap Build Check
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  workflow_dispatch:
    inputs:
          kubernetes-version:
            description: 'Kubernetes Version to build the Snap Package of'
            required: true
            type: string
  workflow_call:
    inputs:
      kubernetes-version:
        description: 'Kubernetes Version to build the Snap Package of'
        required: true
        type: string
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Checkout the repository code
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: microk8s-1.30

      - name: Checkout the main repository code
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-src

      # Run the Pre-Validation Script.
      - name: Run Script on Branch
        run: |
          echo "Running Pre-Validation"
          chmod +x main-src/scripts/config.sh
          chmod +x main-src/scripts/pre-validation.sh
          main-src/scripts/pre-validation.sh ${{ inputs.kubernetes-version }}

      - name: Build Snap Package.
        run: |
          sudo snap install snapcraft --classic
          cd ./microk8s-src/
          sudo snapcraft
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
